# -*- coding: utf-8 -*-
from south.utils import datetime_utils as datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding model 'Proyecto'
        db.create_table(u'db_proyecto', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('nombre', self.gf('django.db.models.fields.CharField')(max_length=40)),
            ('direccion', self.gf('django.db.models.fields.TextField')()),
            ('latitud', self.gf('django.db.models.fields.DecimalField')(max_digits=8, decimal_places=4)),
            ('longitud', self.gf('django.db.models.fields.DecimalField')(max_digits=8, decimal_places=4)),
            ('owner_escritura', self.gf('django.db.models.fields.SmallIntegerField')()),
            ('tipo_adquisicion', self.gf('django.db.models.fields.SmallIntegerField')()),
            ('poblacion_comunidad', self.gf('django.db.models.fields.CharField')(max_length=40)),
            ('nombre_comunidad', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('region', self.gf('django.db.models.fields.CharField')(max_length=30)),
            ('pais', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('ciudad_cercana', self.gf('django.db.models.fields.CharField')(max_length=30)),
            ('distancia_ciudad_cercana', self.gf('django.db.models.fields.PositiveSmallIntegerField')()),
            ('iglesia_cercana', self.gf('django.db.models.fields.CharField')(max_length=30)),
            ('distancia_iglesia_cercana', self.gf('django.db.models.fields.PositiveSmallIntegerField')()),
            ('lengua_primaria', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('fecha_fundacion', self.gf('django.db.models.fields.DateField')()),
            ('ingresos_ofrendas', self.gf('django.db.models.fields.DecimalField')(max_digits=15, decimal_places=3)),
            ('cant_asistentes_adultos', self.gf('django.db.models.fields.SmallIntegerField')()),
            ('cant_asistentes_ninos', self.gf('django.db.models.fields.SmallIntegerField')()),
            ('cant_miembros_adultos', self.gf('django.db.models.fields.SmallIntegerField')()),
            ('cant_miembtos_ninos', self.gf('django.db.models.fields.SmallIntegerField')()),
            ('nombre_pastor', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('entrenamiento_biblico', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('titulos_obtenidos', self.gf('django.db.models.fields.CharField')(max_length=50)),
            ('anios_en_actual_iglesia', self.gf('django.db.models.fields.PositiveSmallIntegerField')()),
            ('anios_en_ministerio', self.gf('django.db.models.fields.PositiveSmallIntegerField')()),
            ('estado_civil', self.gf('django.db.models.fields.SmallIntegerField')()),
            ('cantidad_hijos', self.gf('django.db.models.fields.PositiveSmallIntegerField')()),
            ('q1_disponibilidad_material_estudio_biblico', self.gf('django.db.models.fields.BooleanField')()),
            ('q1_why_not', self.gf('django.db.models.fields.TextField')()),
            ('q2_usa_material_crecimiento_iglesia', self.gf('django.db.models.fields.BooleanField')()),
            ('q2_why_not', self.gf('django.db.models.fields.TextField')()),
            ('q2_how_do', self.gf('django.db.models.fields.TextField')()),
            ('tiempo_terminar_construccion', self.gf('django.db.models.fields.PositiveSmallIntegerField')()),
            ('dimensiones_terreno', self.gf('django.db.models.fields.CharField')(max_length=30)),
            ('dimensiones_edificio', self.gf('django.db.models.fields.CharField')(max_length=30)),
            ('tipo_construccion', self.gf('django.db.models.fields.SmallIntegerField')()),
            ('metodo_construccion', self.gf('django.db.models.fields.SmallIntegerField')()),
            ('requiere_permiso_construccion', self.gf('django.db.models.fields.BooleanField')()),
            ('is_icm_approved', self.gf('django.db.models.fields.BooleanField')()),
            ('moneda_local', self.gf('django.db.models.fields.CharField')(max_length=20)),
            ('dolar_en_moneda_local', self.gf('django.db.models.fields.DecimalField')(max_digits=6, decimal_places=3)),
            ('labor_moneda_local', self.gf('django.db.models.fields.DecimalField')(max_digits=12, decimal_places=3)),
            ('labor_dolares', self.gf('django.db.models.fields.DecimalField')(max_digits=12, decimal_places=3)),
            ('materiales_moneda_local', self.gf('django.db.models.fields.DecimalField')(max_digits=15, decimal_places=3)),
            ('materiales_dolares', self.gf('django.db.models.fields.DecimalField')(max_digits=15, decimal_places=3)),
            ('dinero_moneda_local', self.gf('django.db.models.fields.DecimalField')(max_digits=15, decimal_places=3)),
            ('dinero_dolares', self.gf('django.db.models.fields.DecimalField')(max_digits=15, decimal_places=3)),
            ('terreno_moneda_local', self.gf('django.db.models.fields.DecimalField')(max_digits=12, decimal_places=3)),
            ('terreno_dolares', self.gf('django.db.models.fields.DecimalField')(max_digits=12, decimal_places=3)),
            ('fuente1', self.gf('django.db.models.fields.CharField')(max_length=30)),
            ('aporte_fuente1_monedalocal', self.gf('django.db.models.fields.DecimalField')(max_digits=12, decimal_places=3)),
            ('aporte_fuente1_dolares', self.gf('django.db.models.fields.DecimalField')(max_digits=12, decimal_places=3)),
            ('fuente2', self.gf('django.db.models.fields.CharField')(max_length=30)),
            ('aporte_fuente2_monedalocal', self.gf('django.db.models.fields.DecimalField')(max_digits=12, decimal_places=3)),
            ('aporte_fuente2_dolares', self.gf('django.db.models.fields.DecimalField')(max_digits=12, decimal_places=3)),
            ('aporte_solicitado_monedalocal', self.gf('django.db.models.fields.DecimalField')(max_digits=12, decimal_places=3)),
            ('aporte_solicitado_dolares', self.gf('django.db.models.fields.DecimalField')(max_digits=12, decimal_places=3)),
            ('coste_total_monedalocal', self.gf('django.db.models.fields.DecimalField')(max_digits=12, decimal_places=3)),
            ('coste_total_dolares', self.gf('django.db.models.fields.DecimalField')(max_digits=12, decimal_places=3)),
        ))
        db.send_create_signal(u'db', ['Proyecto'])


    def backwards(self, orm):
        # Deleting model 'Proyecto'
        db.delete_table(u'db_proyecto')


    models = {
        u'db.proyecto': {
            'Meta': {'object_name': 'Proyecto'},
            'anios_en_actual_iglesia': ('django.db.models.fields.PositiveSmallIntegerField', [], {}),
            'anios_en_ministerio': ('django.db.models.fields.PositiveSmallIntegerField', [], {}),
            'aporte_fuente1_dolares': ('django.db.models.fields.DecimalField', [], {'max_digits': '12', 'decimal_places': '3'}),
            'aporte_fuente1_monedalocal': ('django.db.models.fields.DecimalField', [], {'max_digits': '12', 'decimal_places': '3'}),
            'aporte_fuente2_dolares': ('django.db.models.fields.DecimalField', [], {'max_digits': '12', 'decimal_places': '3'}),
            'aporte_fuente2_monedalocal': ('django.db.models.fields.DecimalField', [], {'max_digits': '12', 'decimal_places': '3'}),
            'aporte_solicitado_dolares': ('django.db.models.fields.DecimalField', [], {'max_digits': '12', 'decimal_places': '3'}),
            'aporte_solicitado_monedalocal': ('django.db.models.fields.DecimalField', [], {'max_digits': '12', 'decimal_places': '3'}),
            'cant_asistentes_adultos': ('django.db.models.fields.SmallIntegerField', [], {}),
            'cant_asistentes_ninos': ('django.db.models.fields.SmallIntegerField', [], {}),
            'cant_miembros_adultos': ('django.db.models.fields.SmallIntegerField', [], {}),
            'cant_miembtos_ninos': ('django.db.models.fields.SmallIntegerField', [], {}),
            'cantidad_hijos': ('django.db.models.fields.PositiveSmallIntegerField', [], {}),
            'ciudad_cercana': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'coste_total_dolares': ('django.db.models.fields.DecimalField', [], {'max_digits': '12', 'decimal_places': '3'}),
            'coste_total_monedalocal': ('django.db.models.fields.DecimalField', [], {'max_digits': '12', 'decimal_places': '3'}),
            'dimensiones_edificio': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'dimensiones_terreno': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'dinero_dolares': ('django.db.models.fields.DecimalField', [], {'max_digits': '15', 'decimal_places': '3'}),
            'dinero_moneda_local': ('django.db.models.fields.DecimalField', [], {'max_digits': '15', 'decimal_places': '3'}),
            'direccion': ('django.db.models.fields.TextField', [], {}),
            'distancia_ciudad_cercana': ('django.db.models.fields.PositiveSmallIntegerField', [], {}),
            'distancia_iglesia_cercana': ('django.db.models.fields.PositiveSmallIntegerField', [], {}),
            'dolar_en_moneda_local': ('django.db.models.fields.DecimalField', [], {'max_digits': '6', 'decimal_places': '3'}),
            'entrenamiento_biblico': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'estado_civil': ('django.db.models.fields.SmallIntegerField', [], {}),
            'fecha_fundacion': ('django.db.models.fields.DateField', [], {}),
            'fuente1': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'fuente2': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'iglesia_cercana': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'ingresos_ofrendas': ('django.db.models.fields.DecimalField', [], {'max_digits': '15', 'decimal_places': '3'}),
            'is_icm_approved': ('django.db.models.fields.BooleanField', [], {}),
            'labor_dolares': ('django.db.models.fields.DecimalField', [], {'max_digits': '12', 'decimal_places': '3'}),
            'labor_moneda_local': ('django.db.models.fields.DecimalField', [], {'max_digits': '12', 'decimal_places': '3'}),
            'latitud': ('django.db.models.fields.DecimalField', [], {'max_digits': '8', 'decimal_places': '4'}),
            'lengua_primaria': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'longitud': ('django.db.models.fields.DecimalField', [], {'max_digits': '8', 'decimal_places': '4'}),
            'materiales_dolares': ('django.db.models.fields.DecimalField', [], {'max_digits': '15', 'decimal_places': '3'}),
            'materiales_moneda_local': ('django.db.models.fields.DecimalField', [], {'max_digits': '15', 'decimal_places': '3'}),
            'metodo_construccion': ('django.db.models.fields.SmallIntegerField', [], {}),
            'moneda_local': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'nombre': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'nombre_comunidad': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'nombre_pastor': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'owner_escritura': ('django.db.models.fields.SmallIntegerField', [], {}),
            'pais': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'poblacion_comunidad': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'q1_disponibilidad_material_estudio_biblico': ('django.db.models.fields.BooleanField', [], {}),
            'q1_why_not': ('django.db.models.fields.TextField', [], {}),
            'q2_how_do': ('django.db.models.fields.TextField', [], {}),
            'q2_usa_material_crecimiento_iglesia': ('django.db.models.fields.BooleanField', [], {}),
            'q2_why_not': ('django.db.models.fields.TextField', [], {}),
            'region': ('django.db.models.fields.CharField', [], {'max_length': '30'}),
            'requiere_permiso_construccion': ('django.db.models.fields.BooleanField', [], {}),
            'terreno_dolares': ('django.db.models.fields.DecimalField', [], {'max_digits': '12', 'decimal_places': '3'}),
            'terreno_moneda_local': ('django.db.models.fields.DecimalField', [], {'max_digits': '12', 'decimal_places': '3'}),
            'tiempo_terminar_construccion': ('django.db.models.fields.PositiveSmallIntegerField', [], {}),
            'tipo_adquisicion': ('django.db.models.fields.SmallIntegerField', [], {}),
            'tipo_construccion': ('django.db.models.fields.SmallIntegerField', [], {}),
            'titulos_obtenidos': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        }
    }

    complete_apps = ['db']