# -*- coding: utf-8 -*-

DEPTOS = (	
    ('Amazonas','Amazonas'),
    ('Antioquia','Antioquia'),
    ('Arauca','Arauca'),
    ('Atlantico','Atlántico'),
    ('Bolivar','Bolívar'),
    ('Boyaca','Boyacá'),
    ('Caldas','Caldas'),
    ('Caqueta','Caquetá'),
    ('Casanare','Casanare'),
    ('Cauca','Cauca'),
    ('Cesar','Cesar'),
    ('Choco','Chocó'),
    ('Cundinamarca','Cundinamarca'),
    ('Cordoba','Córdoba'),
    ('Guainia','Guainía'),
    ('Guaviare','Guaviare'),
    ('Huila','Huila'),
    ('La Guajira','La Guajira'),
    ('Magdalena','Magdalena'),
    ('Meta','Meta'),
    ('Narino','Nariño'),
    ('Norte de Santander','Norte de Santander'),
    ('Putumayo','Putumayo'),
    ('Quindio','Quindío'),
    ('Risaralda','Risaralda'),
    ('San Andres','San Andrés'),
    ('Santander','Santander'),
    ('Sucre','Sucre'),
    ('Tolima','Tolima'),
    ('Valle del Cauca','Valle del Cauca'),
    ('Vaupes','Vaupés'),
    ('Vichada','Vichada'),
)

CAPITALES = (

    ('Arauca', 'Arauca'),
    ('Armenia', 'Armenia'),
    ('Barranquilla', 'Barranquilla'),
    ('Bogota', 'Bogotá'),
    ('Bucaramanga', 'Bucaramanga'),
    ('Cali', 'Cali'),
    ('Cartagena', 'Cartagena'),
    ('Cucuta', 'Cúcuta'),
    ('Florencia', 'Florencia'),
    ('Ibague', 'Ibagué'),
    ('Leticia', 'Leticia'),
    ('Manizales', 'Manizales'),
    ('Medellin', 'Medellín'),
    ('Mitu', 'Mitú'),
    ('Monteria', 'Montería'), 
    ('Mocoa', 'Mocoa'), 
    ('Neiva', 'Neiva'),
    ('Pasto', 'Pasto'),
    ('Pereira', 'Pereira'),
    ('Popayan', 'Popayán'),
    ('Puerto Carreno', 'Puerto Carreño'),
    ('Puerto Inirida', 'Puerto Inírida'),
    ('Quibdo', 'Quibdó'),
    ('Riohacha', 'Riohacha'),
    ('San Jose del Guaviare', 'San José del Guaviare'),
    ('Santa Marta', 'Santa Marta'),
    ('San Andres', 'San Andres'),  
    ('Sincelejo', 'Sincelejo'),
    ('Tunja', 'Tunja'),
    ('Valledupar', 'Valledupar'),    
    ('Villavicencio', 'Villavicencio'),
    ('Yopal', 'Yopal'),
)
